### ISSUE TITLE
VIN, Firmware, Watchdog Report

### ISSUE THREAD

**Issue by mlemm99** [astuff/pacmod_dbc#21]
# Original Request Modified!! See Below !!

## VIN Report
Requirement: Add Transmission Rate info to DBC for VIN Report
Message Name: VIN Report
Message ID (Decimal): 1044
Message ID (Hexadecimal): 0x414
Frame Format: Standard
Data Length Code: 8
TX Node: PACMOD
Message Rate: 1 Hz (Proposed)

## Firmware Version Report
Requirement: Add Transmission Rate info to DBC for Firmware Version Report
Message Name: Firmware Version Report
Message ID (Decimal):
Message ID (Hexadecimal):
Frame Format: Standard
Data Length Code: 8
TX Node: PACMOD
Message Rate: 1 Hz (Proposed)

## Watchdog Report
Requirement: Add Transmission Rate and DBC info for Watchdog Report
Message Name: Watchdog Report
Message ID (Decimal): 1536 (Proposed)
Message ID (Hexadecimal): 0x600 (Proposed)
Frame Format: Standard
Data Length Code: 8
TX Node: PACMOD
Message Rate: 10 Hz (Proposed)

**Comment by JWhitleyWork** [comment]
If we are going to make the Watchdog report a real part of the DBC, we should give it a "real" CAN ID, in accordance with https://github.com/astuff/pacmod_dbc/blob/v3/user_can_protocol.md. You OK with this, @mlemm99?

**Comment by mlemm99** [comment]
Changing the CAN ID in firmware is easy. Updating the unknown number of Micros in customer hands will be harder.

We do have another change related to the notification command we could make in unison that would also require Micro updates. Perhaps we plan these changes together so only 1 Micro update needs to be made.

**Comment by asaxsma** [comment]
What is a Watchdog Report?

**Comment by asaxsma** [comment]
Merge Firmware version report request with related issue #10.  APPROVE.
Leave Vin report request.  APPROVE
Create new issue for the watchdog report.  Get message format defined.  Description about not for new development as a heartbeat message.

**Comment by asaxsma** [comment]
Updated request:

VIN Report
Requirement: Add Transmission Rate info to DBC for VIN Report
Message Name: VIN Report
Message ID (Decimal): 1044
Message ID (Hexadecimal): 0x414
Frame Format: Standard
Data Length Code: 8
TX Node: PACMOD
Message Rate: 1 Hz (Proposed)
