### ISSUE TITLE
Create Watchdog Report Message

### ISSUE THREAD

**Issue by asaxsma** [astuff/pacmod_dbc#26]
Watchdog Report
Requirement: Add Transmission Rate and DBC info for Watchdog Report
Message Name: Watchdog Report
Message ID (Decimal): 1536
Message ID (Hexadecimal): 0x600
Frame Format: Standard
Data Length Code: 8
TX Node: PACMOD
Message Rate: 10 Hz

|Name|Type|Bitpos|Length|Factor|Offset|Min|Max|Unit|
|---|---|---|---|---|---|---|---|---|
|GLOBAL_ENABLE_FLAG|Unsigned|0|1|1|0|0|1||
|GLOBAL_OVERRIDE_ACTIVE|Unsigned|1|1|1|0|0|1||
|GLOBAL_COMMAND_TIMEOUT_ERROR|Unsigned|2|1|1|0|0|1||
|GLOBAL_PACMOD_SUBSYSTEM_TIMEOUT|Unsigned|3|1|1|0|0|1||
|GLOBAL_VEHICLE_CAN_TIMEOUT|Unsigned|4|1|1|0|0|1||
|GLOBAL_PACMOD_SYSTEM_FAULT_ACTIVE|Unsigned|5|1|1|0|0|1||
|GLOBAL_CONFIG_FAULT_ACTIVE|Unsigned|6|1|1|0|0|1||
|GLOBAL_TIMEOUT|Unsigned|7|1|1|0|0|1||
|ACCEL_ENABLED|Unsigned|8|1|1|0|0|1||
|ACCEL_OVERRIDE_ACTIVE|Unsigned|9|1|1|0|0|1||
|ACCEL_COMMAND_OUTPUT_FAULT|Unsigned|10|1|1|0|0|1||
|ACCEL_INPUT_OUTPUT_FAULT|Unsigned|11|1|1|0|0|1||
|ACCEL_OUTPUT_REPORTED_FAULT|Unsigned|12|1|1|0|0|1||
|ACCEL_PACMOD_FAULT|Unsigned|13|1|1|0|0|1||
|ACCEL_VEHICLE_FAULT|Unsigned|14|1|1|0|0|1||
|ACCEL_TIMEOUT|Unsigned|15|1|1|0|0|1||
|BRAKE_ENABLED|Unsigned|16|1|1|0|0|1||
|BRAKE_OVERRIDE_ACTIVE|Unsigned|17|1|1|0|0|1||
|BRAKE_COMMAND_OUTPUT_FAULT|Unsigned|18|1|1|0|0|1||
|BRAKE_INPUT_OUTPUT_FAULT|Unsigned|19|1|1|0|0|1||
|BRAKE_OUTPUT_REPORTED_FAULT|Unsigned|20|1|1|0|0|1||
|BRAKE_PACMOD_FAULT|Unsigned|21|1|1|0|0|1||
|BRAKE_VEHICLE_FAULT|Unsigned|22|1|1|0|0|1||
|BRAKE_TIMEOUT|Unsigned|23|1|1|0|0|1||
|SHIFT_ENABLED|Unsigned|24|1|1|0|0|1||
|SHIFT_OVERRIDE_ACTIVE|Unsigned|25|1|1|0|0|1||
|SHIFT_COMMAND_OUTPUT_FAULT|Unsigned|26|1|1|0|0|1||
|SHIFT_INPUT_OUTPUT_FAULT|Unsigned|27|1|1|0|0|1||
|SHIFT_OUTPUT_REPORTED_FAULT|Unsigned|28|1|1|0|0|1||
|SHIFT_PACMOD_FAULT|Unsigned|29|1|1|0|0|1||
|SHIFT_VEHICLE_FAULT|Unsigned|30|1|1|0|0|1||
|SHIFT_TIMEOUT|Unsigned|31|1|1|0|0|1||
|STEER_ENABLED|Unsigned|32|1|1|0|0|1||
|STEER_OVERRIDE_ACTIVE|Unsigned|33|1|1|0|0|1||
|STEER_COMMAND_OUTPUT_FAULT|Unsigned|34|1|1|0|0|1||
|STEER_INPUT_OUTPUT_FAULT|Unsigned|35|1|1|0|0|1||
|STEER_OUTPUT_REPORTED_FAULT|Unsigned|36|1|1|0|0|1||
|STEER_PACMOD_FAULT|Unsigned|37|1|1|0|0|1||
|STEER_VEHICLE_FAULT|Unsigned|38|1|1|0|0|1||
|STEER_TIMEOUT|Unsigned|39|1|1|0|0|1||
|MOD1_CONFIG_FAULT|Unsigned|40|1|1|0|0|1||
|MOD1_CAN_TIMEOUT|Unsigned|41|1|1|0|0|1||
|MOD1_COUNTER_FAULT|Unsigned|42|1|1|0|0|1||
|MOD2_CONFIG_FAULT|Unsigned|43|1|1|0|0|1||
|MOD2_CAN_TIMEOUT|Unsigned|44|1|1|0|0|1||
|MOD2_COUNTER_FAULT|Unsigned|45|1|1|0|0|1||
|MOD3_CONFIG_FAULT|Unsigned|46|1|1|0|0|1||
|MOD3_CAN_TIMEOUT|Unsigned|47|1|1|0|0|1||
|MOD3_COUNTER_FAULT|Unsigned|48|1|1|0|0|1||
|MINI1_RPT_TIMEOUT|Unsigned|49|1|1|0|0|1||
|MINI1_CONFIG_FAULT|Unsigned|50|1|1|0|0|1||
|MINI1_CAN_TIMEOUT|Unsigned|51|1|1|0|0|1||
|MINI1_COUNTER_FAULT|Unsigned|52|1|1|0|0|1||
|MINI2_RPT_TIMEOUT|Unsigned|53|1|1|0|0|1||
|MINI2_CONFIG_FAULT|Unsigned|54|1|1|0|0|1||
|MINI2_CAN_TIMEOUT|Unsigned|55|1|1|0|0|1||
|MINI2_COUNTER_FAULT|Unsigned|56|1|1|0|0|1||
|MINI3_RPT_TIMEOUT|Unsigned|57|1|1|0|0|1||
|MINI3_CONFIG_FAULT|Unsigned|58|1|1|0|0|1||
|MINI3_CAN_TIMEOUT|Unsigned|59|1|1|0|0|1||
|MINI3_COUNTER_FAULT|Unsigned|60|1|1|0|0|1||
|MOD_SYSTEM_PRESENT_FAULT|Unsigned|61|1|1|0|0|1||
|MINI_SYSTEM_PRESENT_FAULT|Unsigned|62|1|1|0|0|1||

**Comment by asaxsma** [comment]
@mlemm99 will you please enter the message format in this issue according the template instructions.

**Comment by JWhitleyWork** [comment]
Closed by #42.
