### ISSUE TITLE
Remove Unused Report 0x41A

### ISSUE THREAD

**Issue by mlemm99** [astuff/pacmod_dbc#31]
## Proposal
Remove unused CAN ID 0x41A
Remove unused system report ANG_VEL_RPT

AutonomouStuff does not have any platforms that use this report.

**Comment by asaxsma** [comment]
This was a customer request on Lexus that was part of Change 003 approved on 2/14/2019.  See legacy change long.

**Comment by asaxsma** [comment]
Moved to BitBucket.
