### ISSUE TITLE
Parking Brake Report / Hazard Lights Report

### ISSUE THREAD

**Issue by mlemm99** [astuff/pacmod_dbc#33]
## Overview
The Parking Brake Report and Hazard Lights Report bits/bytes do not match the Horn System

## Proposal
Modify the Parking Brake Report and Hazard Lights Report to Match the system type.

Message Name: PARKING_BRAKE_RPT
Message ID (Decimal): 548
Message ID (Hexadecimal): 0x224
Frame Format: Standard
Data Length Code: 8 (Future: 4)
TX Node: PACMOD
Message Rate: 30 Hz

Message Name: HAZARD_LIGHTS_RPT
Message ID (Decimal): 532
Message ID (Hexadecimal): 0x214
Frame Format: Standard
Data Length Code: 8 (Future: 4)
TX Node: PACMOD
Message Rate: 30 Hz

Current:

|Name|Type|Bitpos|Length|Factor|Offset|Min|Max|Unit|
|---|---|---|---|---|---|---|---|---|
|ENABLED|Unsigned|0|1|1|0|0|1||
|OVERRIDE_ACTIVE|Unsigned|1|1|1|0|0|1||
|COMMAND_OUTPUT_FAULT|Unsigned|2|1|1|0|0|1||
|INPUT_OUTPUT_FAULT|Unsigned|3|1|1|0|0|1||
|OUTPUT_REPORTED_FAULT|Unsigned|4|1|1|0|0|1||
|PACMOD_FAULT|Unsigned|5|1|1|0|0|1||
|VEHICLE_FAULT|Unsigned|6|1|1|0|0|1||
|COMMAND_TIMEOUT|Unsigned|7|1|1|0|0|1|||
|MANUAL_INPUT|Unsigned|8|1|1|0|0|1||
|COMMANDED_VALUE|Unsigned|16|1|1|0|0|1||
|OUTPUT_VALUE|Unsigned|24|1|1|0|0|1||

Proposed:

|Name|Type|Bitpos|Length|Factor|Offset|Min|Max|Unit|
|---|---|---|---|---|---|---|---|---|
|ENABLED|Unsigned|0|1|1|0|0|1||
|OVERRIDE_ACTIVE|Unsigned|1|1|1|0|0|1||
|COMMAND_OUTPUT_FAULT|Unsigned|2|1|1|0|0|1||
|INPUT_OUTPUT_FAULT|Unsigned|3|1|1|0|0|1||
|OUTPUT_REPORTED_FAULT|Unsigned|4|1|1|0|0|1||
|PACMOD_FAULT|Unsigned|5|1|1|0|0|1||
|VEHICLE_FAULT|Unsigned|6|1|1|0|0|1||
|COMMAND_TIMEOUT|Unsigned|7|1|1|0|0|1|||
|MANUAL_INPUT|Unsigned|8|**8**|1|0|0|1||
|COMMANDED_VALUE|Unsigned|16|**8**|1|0|0|1||
|OUTPUT_VALUE|Unsigned|24|**8**|1|0|0|1||

**Comment by asaxsma** [comment]
Can you bold the differences.  Thanks!
