### ISSUE TITLE
Add Sprayer Command

### ISSUE THREAD

**Issue by mlemm99** [astuff/pacmod_dbc#37]
## Overview
Add ability to command windshield sprayer

## Message
Message Name: SPRAYER_CMD
Message ID (Decimal): 312
Message ID (Hexadecimal): 0x138
Frame Format: Standard
Data Length Code: 8 (Future: 2)
TX Node: PACMOD
Message Rate: 30 Hz

## Proposed
|Name|Type|Bitpos|Length|Factor|Offset|Min|Max|Unit|
|---|---|---|---|---|---|---|---|---|
|ENABLE|Unsigned|0|1|1|0|0|1||
|IGNORE_OVERRIDES|Unsigned|1|1|1|0|0|1||
|CLEAR_OVERRIDE|Unsigned|2|1|1|0|0|1||
|SPRAYER_CMD  **1**|Unsigned|8|1|1|0|0|1||

**1**
0 = NOT SPRAYING, 1 = SPRAYING

**Comment by asaxsma** [comment]
Probably need report too.
