### ISSUE TITLE
Move the authoritative description of the CAN Protocol from the PACMod User Manual to the user_can_protocol.md.information from the CAN 

### ISSUE THREAD

**Issue by asaxsma** [astuff/pacmod_dbc#48]
Keep protocol information in one place.

**Comment by asaxsma** [comment]
Guys, we'll be approving this at our next CAN API meeting.  Please take a look.  Its is basically a move of the authoritative CAN API description from the PACMod System User manual to the pacmod_dbc repository.  I've pushed it and so its available to view.  Please provide feedback.

**Comment by JWhitleyWork** [comment]
I'm on-board. Approved.
