### ISSUE TITLE
Convert Remaining is_valid to avail

### ISSUE THREAD

**Issue by mlemm99** [astuff/pacmod_dbc#49]
## Overview
Convert Remaining is_valid values to avail with the exception of vehicle speed.

The outstanding reports to convert include...

**Occupancy Report**
**Door Report**
**Interior Light Report**
**Rear Lights Report**

**Comment by JWhitleyWork** [comment]
I approve.

**Comment by driscoll85** [comment]
Approved

**Comment by asaxsma** [comment]
FYI - These weren't converted the first time on #36 because they are not aux reports.  Mike and I had a conversation to confirm these were in fact used similarly.

**Comment by asaxsma** [comment]
Moved to bitbucket
